services:

  postgres:
    image: postgres:16.2
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_USER: $PGUSER